name: Continuous Integration/ Continuous Deployment
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Node LTS versions
      uses: msimerson/node-lts-versions@v1.1.1
    - run: npm install --force
    - run: npm start &
    
    - name: adding aws cred
      run: sed -i 's|"access_key_id"|${{secrets.ACCESS_KEY}}|g;s|"secret_key_id"|${{secrets.AWS_SEC_KEY}}|g' index.js
      shell: bash
      
    - name: Docker Login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Docker Push
      env:
        REPO: ingest-ms
        AWS_ACCESS_KEY: ${{secrets.ACCESS_KEY}}
        AWS_SECRET_KEY: ${{secrets.AWS_SEC_KEY}}
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest ${{secrets.DOCKER_USER}}/$REPO:latest
        docker push ${{secrets.DOCKER_USER}}/$REPO
    - name: Docker pull image and deploy from hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        REPO: ingest-ms
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker login
          docker pull asifbashaabdul/ingest-ms
          docker stop ingest_app || true
          docker rm ingest_app || true  
          docker run -d --name ingest_app -p 8080:8080 asifbashaabdul/ingest-ms
